# Generated by Django 4.0.5 on 2022-09-13 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publishers', '0036_alter_article_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='full_name')),
                ('email', models.EmailField(max_length=50, verbose_name='email')),
                ('phone_number', models.CharField(max_length=50, verbose_name='phone_number')),
                ('address', models.CharField(max_length=256, verbose_name='address')),
                ('evalator_speech', models.TextField(verbose_name='evalator_speech')),
                ('cv', models.FileField(upload_to='', verbose_name='cv')),
                ('selected', models.BooleanField(default=False, verbose_name='selected')),
                ('employed', models.BooleanField(default=False, verbose_name='employed')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publishers.article', verbose_name='post')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
            },
        ),
    ]
