# Generated by Django 4.0.5 on 2022-09-13 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='evalator_speech',
            new_name='evelator_speech',
        ),
    ]
