# Generated by Django 4.0.5 on 2022-09-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_rename_evalator_speech_application_evelator_speech'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='evelator_speech',
            field=models.TextField(verbose_name='evelator_speech'),
        ),
    ]
