# Generated by Django 4.0.5 on 2022-09-15 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0038_alter_article_section'),
        ('application', '0003_alter_application_evelator_speech'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_applications', to='publishers.article', verbose_name='post'),
        ),
    ]
