# Generated by Django 2.1.7 on 2019-08-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'managed': True, 'ordering': ['-pub_date'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(height_field=250, null=True, upload_to='publisher/static/publishers', width_field=250),
        ),
    ]
