# Generated by Django 2.1.7 on 2019-08-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0006_auto_20190817_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(null=True, upload_to='homeview/static/homeview/images'),
        ),
    ]
