# Generated by Django 2.1.7 on 2019-08-21 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0008_auto_20190817_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_heading', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('body_text', models.TextField()),
            ],
            options={
                'verbose_name': 'Sections',
                'verbose_name_plural': 'Sections',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='sub_heading',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='sections',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='publishers.Sections'),
        ),
    ]
