# Generated by Django 2.1.7 on 2019-08-21 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0009_auto_20190821_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='headline',
            new_name='title',
        ),
    ]
