# Generated by Django 2.1.7 on 2019-08-21 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0010_auto_20190821_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sections',
            old_name='image',
            new_name='Sub_section_image',
        ),
    ]
