# Generated by Django 2.1.7 on 2019-08-21 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0011_auto_20190821_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='sections',
        ),
        migrations.AddField(
            model_name='sections',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='publishers.Article'),
        ),
    ]
