# Generated by Django 2.1.7 on 2019-08-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0012_auto_20190821_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sections',
            name='body_text',
            field=models.TextField(null=True),
        ),
    ]
