# Generated by Django 2.1.7 on 2019-08-21 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0013_auto_20190821_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sections',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='publishers.Article'),
        ),
    ]
