# Generated by Django 2.1.7 on 2019-08-30 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0014_auto_20190821_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title_slug',
            field=models.SlugField(default='null'),
        ),
    ]
