# Generated by Django 2.1.7 on 2019-09-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0017_auto_20190830_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sections',
            name='Sub_section_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sections',
            name='sub_heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
