# Generated by Django 2.1.7 on 2019-09-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0018_auto_20190903_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sections',
            name='sub_heading',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
