# Generated by Django 2.1.7 on 2019-10-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0019_auto_20190903_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='n_comments',
        ),
        migrations.RemoveField(
            model_name='article',
            name='n_pingbacks',
        ),
        migrations.RemoveField(
            model_name='article',
            name='rating',
        ),
        migrations.AddField(
            model_name='article',
            name='image_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sections',
            name='image_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
