# Generated by Django 2.1.7 on 2019-10-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0020_auto_20191002_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
