# Generated by Django 2.1.7 on 2019-10-18 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0023_auto_20191018_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(),
        ),
    ]
