# Generated by Django 2.1.7 on 2019-11-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0027_auto_20191126_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='description',
            field=models.TextField(max_length=150, null=True, verbose_name='description'),
        ),
    ]
