# Generated by Django 2.1.7 on 2020-03-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0029_auto_20200304_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sections',
            name='image_decription',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
