# Generated by Django 4.0.5 on 2022-09-12 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0034_alter_article_id_alter_publisher_id_alter_section_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='references',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='section',
        ),
    ]
