# Generated by Django 4.0.5 on 2022-09-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0036_alter_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='still_open',
            field=models.BooleanField(default=True),
        ),
    ]
